export type Link = { id: string; label: string };
export type Service = {
  id: string; icon: string; title: string; featured?: boolean; description: string;
  deliverables: string[]; stack: string[]; timeline: string; fit: string; more: string[];
};
export type Project = {
  id: string; kinds: string[]; title: string; category: string; image: string; skills: string[];
  stack: [string, string][]; githubUrl?: string; liveUrl?: string; description: string; long: string;
  built: string[]; platform: string; screens?: string[];
};
export type ProcessItem = { step: string; title: string; duration: string; description: string };
export type Experience = { logo: string; company: string; role: string; period: string; points: string[]; last?: boolean; current?: boolean };
export type Faq = { q: string; a: string };
export type SiteData = {
  contact: { email: string; phone: string; location: string; github: string; githubLabel: string; linkedin: string; linkedinLabel: string };
  links: Link[]; services: Service[]; projects: Project[]; process: ProcessItem[]; experience: Experience[];
  stack: [string, string][]; stackMore: [string, string][]; faq: Faq[];
};

export const site: SiteData = {
  contact: { email: 'ralphsaridar@hotmail.com', phone: '+961 70 386 361', location: 'Awkar, Lebanon · works remotely', github: 'https://github.com/RalphSaridar369', githubLabel: 'github.com/RalphSaridar369', linkedin: 'https://www.linkedin.com/in/ralph-saridar-7278021b3/', linkedinLabel: 'linkedin.com/in/ralph-saridar' },
  links: [{ id: 'services', label: 'Services' }, { id: 'work', label: 'Work' }, { id: 'process', label: 'Process' }, { id: 'experience', label: 'Experience' }, { id: 'faq', label: 'FAQ' }, { id: 'contact', label: 'Contact' }],
  services: [
    { id: 'mvp', icon: 'rocket', title: 'MVPs & full-stack apps', featured: true, description: 'From a blank repo to a product your first users can log into. Database, API and interface, built by one person who owns all of it.', deliverables: ['Auth, roles and admin panel', 'Deployed on DigitalOcean with CI', 'Handover docs your next hire can read'], stack: ['React', 'Node.js', 'PostgreSQL'], timeline: '6–10 weeks', fit: 'You have an idea and a first set of users, and need a working product to put in front of them.', more: ['Scoped feature list and data model', 'REST API with documentation', 'React web app or React Native app', 'Staging and production environments', 'Up to 3 months of fixes after launch'] },
    { id: 'mobile', icon: 'smartphone', title: 'Mobile apps', description: 'Cross-platform apps for iOS and Android from a single React Native codebase.', deliverables: ['App Store + Play Store release', 'Push notifications and payments', 'Offline-friendly data'], stack: ['React Native', 'TypeScript'], timeline: '6–12 weeks', fit: 'You need your product on phones without paying for two separate native builds.', more: ['One codebase for iOS and Android', 'Store listings and release builds', 'Push notifications', 'Payments integration', 'Backend API if you don\u2019t have one'] },
    { id: 'backend', icon: 'database', title: 'Backend & APIs', description: 'Fast, documented APIs and databases that hold up when traffic grows.', deliverables: ['REST APIs with full documentation', 'Query and performance tuning', 'Email, SMS and websocket integrations'], stack: ['NestJS', 'TypeORM', 'PostgreSQL'], timeline: '3–8 weeks', fit: 'Your front end is ahead of your backend, or your database is slowing the product down.', more: ['API design and documentation', 'PostgreSQL schema and migrations', 'Query profiling and optimisation', 'Transactional email, cron jobs, websockets', 'Deployment and monitoring'] },
    { id: 'web', icon: 'code-xml', title: 'Web apps & frontend', description: 'Interactive React front ends that plug cleanly into your existing API.', deliverables: ['Reusable component library', 'Role-based access in the UI', 'Responsive on every screen'], stack: ['React', 'Next.js', 'Tailwind'], timeline: '4–8 weeks', fit: 'You already have an API and need a front end your users can rely on.', more: ['React app wired to your API', 'Reusable components', 'Role-based access control', 'Responsive layouts', 'Tests with Jest and Cypress'] },
    { id: 'landing', icon: 'layout-template', title: 'Landing pages', description: 'A quick, responsive page that explains your product and collects sign-ups.', deliverables: ['Live in about a week', 'Forms wired to your inbox or CRM', 'Lighthouse 90+'], stack: ['Next.js', 'HTML/CSS'], timeline: '1–2 weeks', fit: 'You\u2019re about to launch or raise and need a page that explains the product.', more: ['Responsive page from your copy', 'Sign-up or contact form', 'Analytics setup', 'Hosting and domain setup', 'One round of revisions'] },
    { id: 'ecom', icon: 'shopping-bag', title: 'E-commerce', description: 'Storefronts and B2B ordering flows: catalogue, cart, checkout, dashboard.', deliverables: ['Product filtering and search', 'Cart and checkout flow', 'Order and customer dashboard'], stack: ['React Native', 'Node.js'], timeline: '6–10 weeks', fit: 'You sell products or run B2B ordering and need a custom store or ordering app.', more: ['Catalogue with filters and search', 'Cart and checkout', 'Payments integration', 'Order and customer dashboard', 'Admin for products and stock'] }
  ],
  projects: [
    { id: 'sieltec', kinds: ['client'], title: 'Sieltec', category: 'Client · Website', image: '/assets/projects/sieltec.png', skills: ['react', 'typescript', 'cloudflare'], stack: [['reactjs', 'React'], ['typescript', 'TypeScript'], ['https://cdn.simpleicons.org/cloudflare', 'Cloudflare'], ['https://unpkg.com/lucide-static@0.460.0/icons/mail.svg', 'Custom email integration']], githubUrl: '', liveUrl: 'https://sieltecltd.com/', description: 'A multi-page site for a logistics and trade startup, with scroll animations and a custom contact form.', long: "Built the website for Sieltec, a startup positioning itself as a bridge between complex markets, delivering logistics and trade solutions with a focus on integrity and expertise. Developed a clean, professional site with smooth scroll-triggered animations, multi-page navigation, and a custom-integrated contact form, helping a solo founder present their business clearly and credibly to potential partners and clients.", built: ['Multi-page navigation', 'Scroll-triggered animations', 'Custom-integrated contact form'], platform: 'Web' },
    { id: 'talts', kinds: ['client', 'mobile'], title: 'TALTS DG Road Transport Guide', category: 'Client · Mobile app', image: '/assets/projects/talts.png', skills: ['react-native', 'expo-router', 'revenuecat'], stack: [['reactjs', 'React Native'], ['https://cdn.simpleicons.org/expo', 'Expo Router'], ['typescript', 'TypeScript'], ['https://cdn.simpleicons.org/revenuecat', 'RevenueCat'], ['reactjs', 'React Context API']], githubUrl: '', liveUrl: '', description: 'Regulatory guidance for moving dangerous goods by road in Australia, with Hazchem lookup and subscriptions.', long: "A mobile app providing regulatory guidance for the safe transport of dangerous goods and explosives by road in Australia. Covers placarding, safety equipment, and segregation requirements across all 14 dangerous goods classes, plus container-specific rules for drums, portable tanks, road tankers, and explosives categories 1–3. References ADG7, AEC3, WA legislation, and Australian Standards, with built-in Hazchem code lookup and Emergency Information Panel guidance. Built with React Native and Expo Router, using TypeScript throughout. Implements a subscription model via RevenueCat and includes screen capture prevention to protect regulated content.", built: ['Guidance across all 14 dangerous goods classes', 'Hazchem code lookup', 'RevenueCat subscriptions', 'Screen capture prevention'], platform: 'iOS and Android' },
    { id: 'flowlight', kinds: ['client'], title: 'The Flow Light', category: 'Client · Portfolio site', image: '/assets/projects/flowlight.png', skills: ['react', 'typescript', 'cdn'], stack: [['reactjs', 'React'], ['https://cdn.simpleicons.org/reactrouter', 'React Router'], ['typescript', 'TypeScript'], ['https://unpkg.com/lucide-static@0.460.0/icons/globe.svg', 'CDN integration']], githubUrl: '', liveUrl: 'https://theflowlight.com/', description: 'A responsive photography portfolio with category filtering, CDN-served images and Netlify deploys.', long: "Designed and built a modern, responsive portfolio website for photographer/videographer Jack Yammouni, showcasing work across product, fashion, band, portrait, and documentary photography. The site features dynamic category filtering, a fully responsive layout with tailored breakpoints for desktop through mobile, and subtle scroll and hover animations for a polished, professional feel. Images are served through a CDN for fast load times, with a lightweight content pipeline that makes adding new work straightforward. Deployed on Netlify with automatic builds from GitHub and edge caching for performance.", built: ['Dynamic category filtering', 'CDN-served images', 'Automatic Netlify builds from GitHub'], platform: 'Web' },
    { id: 'wareviews', kinds: ['personal'], title: 'WhatsApp Reviews Data Clustering', category: 'Personal · Data + web app', image: '/assets/projects/wa-reviews.png', skills: ['python', 'nlp', 'react'], stack: [['https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/icons/python/python-original.svg', 'Python'], ['https://unpkg.com/lucide-static@0.460.0/icons/chart-scatter.svg', 'UMAP'], ['https://unpkg.com/lucide-static@0.460.0/icons/boxes.svg', 'HDBSCAN'], ['https://unpkg.com/lucide-static@0.460.0/icons/bot.svg', 'LLM integration'], ['reactjs', 'React'], ['typescript', 'TypeScript']], githubUrl: '', liveUrl: 'https://wa-reviews-analysis.netlify.app/', description: 'A pipeline that clusters 10,000+ app store reviews into 66 labelled themes, with a web app to explore them.', long: "Built an end-to-end pipeline that turns raw app store reviews into actionable product insights. The system cleans and embeds review text, then uses UMAP + HDBSCAN to cluster semantically similar reviews into distinct themes. An LLM generates a human-readable label and sentiment summary for each cluster, alongside its average rating — condensing 10,000+ unstructured reviews into 66 clear, skimmable themes. Paired with a lightweight web app for interactive exploration, so teams can browse clusters without digging through spreadsheets.", built: ['Review cleaning and embeddings', 'UMAP + HDBSCAN clustering', 'LLM-generated labels and sentiment', 'Web app for browsing clusters'], platform: 'Web' },
    { id: 'space', kinds: ['personal'], title: 'Space Library', category: 'Personal · Web app', image: '/assets/projects/space-library.png', skills: ['react', 'scss'], stack: [['reactjs', 'React'], ['css', 'SCSS'], ['javascript', 'JavaScript']], githubUrl: 'https://github.com/RalphSaridar369/Space_Gallery_App', liveUrl: 'https://space-library.netlify.app/', description: 'A web app that uses NASA\u2019s API to show images and data on planets, stars and galaxies.', long: 'Space Library uses NASA\u2019s API to show images and detailed data on planets, stars and galaxies, in an interface that makes the archive easy to browse.', built: ['API integration and caching', 'Responsive gallery layout', 'Search and detail views'], platform: 'Web' },
    { id: 'bull', kinds: ['personal', 'mobile'], title: 'Bull Market', category: 'Personal · Mobile app', image: '/assets/projects/bull-market.jpeg', skills: ['react-native'], stack: [['reactjs', 'React Native'], ['javascript', 'JavaScript']], githubUrl: 'https://github.com/RalphSaridar369/CryptoApp-ReactNative', description: 'An all-in-one crypto app: live coin prices, community news and an APY calculator.', long: 'Bull Market is an all-in-one crypto app with real-time coin price tracking, community news and an APY calculator.', built: ['Real-time price tracking', 'News feed', 'APY calculator'], platform: 'iOS and Android' },
    { id: 'cart', kinds: ['personal', 'mobile'], title: 'Ecommerce', category: 'Personal · Mobile app', image: '/assets/projects/smart-cart.png', skills: ['react-native'], stack: [['reactjs', 'React Native'], ['javascript', 'JavaScript']], githubUrl: 'https://github.com/RalphSaridar369/ReactNative_Ecommerce', description: 'A template for a tech-focused store: dashboard, filters, cart and checkout.', long: 'A template for a tech-focused ecommerce app. Users get a dashboard, browse and filter products, manage their cart and complete checkout.', built: ['Product browsing and filters', 'Cart management', 'Checkout flow'], platform: 'iOS and Android' }
  ],
  process: [
    { step: '01', title: 'Discovery call', duration: '30 min', description: 'We talk through what you\u2019re building, who it\u2019s for and what launch looks like.' },
    { step: '02', title: 'Proposal', duration: '2–3 days', description: 'A written scope with milestones, timeline and a fixed price per milestone.' },
    { step: '03', title: 'Build', duration: 'weekly demos', description: 'You get a staging link in week one and a demo every week after that.' },
    { step: '04', title: 'Launch & support', duration: 'up to 3 months', description: 'I deploy, monitor and fix anything that comes up for up to 3 months after launch.' }
  ],
  experience: [
    { logo: '/assets/companies/optidist.png', company: 'OptiDist', role: 'Back End Engineer', period: 'Jul 2022 — Jun 2026', points: ['Led backend development for B2B marketplace systems using Node.js, TypeORM and PostgreSQL.', 'Optimized complex PostgreSQL queries, reducing response times and improving scalability.', 'Wrote API documentation for internal and external stakeholders.', 'Integrated Postmark and DigitalOcean to improve platform reliability.'] },
    { logo: '/assets/companies/globalistic.png', company: 'Globalistic', role: 'Front End Developer', period: 'Sep 2021 — Mar 2022', last: true, points: ['Built large-scale B2B marketplace apps in React and React Native.', 'Built interactive 3D features with Babylon.js, rendering real-time data on component movement.', 'Implemented role-based access control for different user types and permissions.'] }
  ],
  stack: [['/assets/tech/reactjs.png', 'React'], ['/assets/tech/reactjs.png', 'React Native'], ['https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/icons/nextjs/nextjs-original.svg', 'Next.js'], ['/assets/tech/nodejs.png', 'Node.js'], ['https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/icons/nestjs/nestjs-plain.svg', 'NestJS'], ['', 'TypeORM'], ['/assets/tech/postgresql.png', 'PostgreSQL'], ['/assets/tech/typescript.png', 'TypeScript']],
  stackMore: [['/assets/tech/javascript.png', 'JavaScript'], ['/assets/tech/html.png', 'HTML'], ['/assets/tech/css.png', 'CSS'], ['/assets/tech/mysql.png', 'MySQL'], ['/assets/tech/mongodb.png', 'MongoDB'], ['/assets/tech/git.png', 'Git']],
  faq: [
    { q: 'How do you price a project?', a: 'After the discovery call I send a written proposal with milestones and a fixed price for each one. You pay per milestone, so you always know what the next step costs.' },
    { q: 'Who owns the code?', a: 'You do. The repository lives in your GitHub organisation from day one, and every account I set up is in your name.' },
    { q: 'What happens after launch?', a: 'Fixes are included for up to 3 months after launch. After that I can stay on a monthly retainer or hand over to your team with documentation.' },
    { q: 'Which time zone do you work in?', a: 'I\u2019m in Lebanon (GMT+3) and work remotely. My hours overlap with Europe for the full day and with the US East Coast in the morning.' }
  ]
};
